// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMOMUUHSL6KtD0UY8iSXi1bNddq7G5kaE',
    appId: '1:1069173277238:web:3aff5b8e5d3997b7354e97',
    messagingSenderId: '1069173277238',
    projectId: 'clg-project-a8925',
    authDomain: 'clg-project-a8925.firebaseapp.com',
    storageBucket: 'clg-project-a8925.firebasestorage.app',
    measurementId: 'G-LV929EPHZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD29K8CVbmX23hfD8JcLUs3V92Qt4yFj_8',
    appId: '1:1069173277238:android:9e14b4f349af913d354e97',
    messagingSenderId: '1069173277238',
    projectId: 'clg-project-a8925',
    storageBucket: 'clg-project-a8925.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPM9izgCNZ-cEWAGtjZhAMcSZ_okrwzdo',
    appId: '1:1069173277238:ios:8ecbcf4828b662a6354e97',
    messagingSenderId: '1069173277238',
    projectId: 'clg-project-a8925',
    storageBucket: 'clg-project-a8925.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

}